version: '3.8'

services:
  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_1
    ports:
      - "3333:8001"
    environment:
      - NODE_ENV=${secrets.NODE_ENV}
    networks:
      - app-network

  backend2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_2
    ports:
      - "4444:8001"
    environment:
      - NODE_ENV=${secrets.NODE_ENV}
    networks:
      - app-network

  backend3:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_3
    ports:
      - "5555:8001"
    environment:
      - NODE_ENV=${secrets.NODE_ENV}
    networks:
      - app-network

  backend4:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_4
    ports:
      - "6666:8001"
    environment:
      - NODE_ENV=${secrets.NODE_ENV}
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
